ProiectLicenta/Models/RegistruTratamente.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProiectLicenta.Models
{
    public class RegistruTratamente
    {
        [Key]
        public int CodTratamentAplicat { get; set; }
        [ForeignKey("Parcela")]
        public int CodParcela { get; set; }
        [ForeignKey("Daunatori")]
        public int CodDaunator { get; set; }
        [Required]
        public int Suprafata { get; set; }
        [ForeignKey("Angajat")]
        public int CodAngajat { get; set; }
        [Required]
        public DateTime DataAplicare { get; set; }
        public bool Stare { get; set; }
        public Angajat? Angajat { get; set; }
        public Parcela? Parcela { get; set; }
        public Daunatori? Daunatori { get; set; }
        public RegistruTratamente(int codTratamentAplicat, int codParcela, int codDaunator, int suprafata, int codAngajat, DateTime dataAplicare,bool stare)
        {
            this.CodTratamentAplicat = codTratamentAplicat;
            this.CodParcela = codParcela;
            this.CodDaunator = codDaunator;
            this.Suprafata = suprafata;
            this.CodAngajat = codAngajat;
            this.DataAplicare = dataAplicare;
            this.Stare = stare;
        }
    }
}

ProiectLicenta/Controllers/RegistruTratamenteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ProiectLicenta.Data;
using ProiectLicenta.Models;
using ProiectLicenta.ViewModels;

namespace ProiectLicenta.Controllers
{
    [Authorize]
    public class RegistruTratamenteController : Controller
    {

        private ApplicationDbContext context;
        public RegistruTratamenteController(ApplicationDbContext dbcontext)
        {
            this.context = dbcontext;
        }
        [HttpGet]
        public ActionResult Index(string sortOrder,string searchString)
        {
            ViewBag.SortOrder = sortOrder;
            ViewBag.CurrentFilter = searchString;
            if (!string.IsNullOrEmpty(searchString))
            {
                if (int.TryParse(searchString, out int index))
                {
                    List<RegistruTratamente> datetratamente = SortData(context.RegistruTratamente.Include(r => r.Parcela).Include(r => r.Angajat).Include(r => r.Daunatori).ThenInclude(r => r.Tratament).Where(a => a.Parcela.Locatie.Contains(searchString) && a.Stare == true ||
                 a.Angajat.Nume.Contains(searchString) || a.Angajat.Prenume.Contains(searchString) || a.Daunatori.Denumire.Contains(searchString) || a.Daunatori.Tratament.Denumire.Contains(searchString) || a.Suprafata == index).ToList(), sortOrder);
                    return View(datetratamente);
                }
                else
                {
                    List<RegistruTratamente> datetratamente = SortData(context.RegistruTratamente.Include(r => r.Parcela).Include(r => r.Angajat).Include(r => r.Daunatori).ThenInclude(r => r.Tratament).Where(a => a.Parcela.Locatie.Contains(searchString) && a.Stare == true ||
                 a.Angajat.Nume.Contains(searchString) || a.Angajat.Prenume.Contains(searchString) || a.Daunatori.Denumire.Contains(searchString) || a.Daunatori.Tratament.Denumire.Contains(searchString)).ToList(), sortOrder);
                    return View(datetratamente);
                }
            }
            List<RegistruTratamente> registruTratamente = SortData(context.RegistruTratamente.Include(r => r.Parcela).Include(r => r.Angajat).Include(r => r.Daunatori).ThenInclude(r => r.Tratament).Where(a => a.Stare == true).ToList(), sortOrder);
            return View(registruTratamente);
        }
        public void CheiExterne(AddRegistruTratamenteViewModel intrare)
        {
            var codAngajat = context.Angajat.OrderBy(p => p.Nume).ToList();
            ViewBag.codAngajat = codAngajat.Select(p => new SelectListItem
            {
                Value = p.CodAngajat.ToString(),
                Text = p.Nume + " " + p.Prenume,
                Selected = p.CodAngajat == intrare.CodAngajat,
            });
            var codParcela = context.Parcela.OrderBy(p => p.Locatie).ToList();
            ViewBag.codParcela = codParcela.Select(p => new SelectListItem
            {
                Value = p.CodParcela.ToString(),
                Text = p.Locatie,
                Selected = p.CodParcela == intrare.CodParcela,
            });
            var codDaunator = context.Daunatori.OrderBy(p => p.Denumire).ToList();
            ViewBag.codDaunator = codDaunator.Select(p => new SelectListItem
            {
                Value = p.CodDaunator.ToString(),
                Text = p.Denumire,
                Selected = p.CodDaunator == intrare.CodDaunator,
            });

        }
        [HttpGet]
        public IActionResult Adaugare()
        {
            AddRegistruTratamenteViewModel addRegistruTratamenteViewModel = new AddRegistruTratamenteViewModel();
            CheiExterne(addRegistruTratamenteViewModel);
            addRegistruTratamenteViewModel.DataAplicare = DateTime.Today;
            return View(addRegistruTratamenteViewModel);
        }
        [HttpPost]
        public IActionResult Adaugare(AddRegistruTratamenteViewModel addRegistruTratamenteViewModel)
        {
            if (ModelState.IsValid)
            {
                RegistruTratamente newRegistruTratamente = new RegistruTratamente(
                    addRegistruTratamenteViewModel.CodTratamentAplicat,
                    addRegistruTratamenteViewModel.CodParcela,
                    addRegistruTratamenteViewModel.CodDaunator,
                    addRegistruTratamenteViewModel.Suprafata,
                    addRegistruTratamenteViewModel.CodAngajat,
                    addRegistruTratamenteViewModel.DataAplicare,
                    addRegistruTratamenteViewModel.Stare
                );

                context.RegistruTratamente.Add(newRegistruTratamente);
                context.SaveChanges();
                return Redirect("/RegistruTratamente");
            }
            return Adaugare();
        }
        public IActionResult Stergere(string searchString)
        {
            ViewBag.CurrentFilter = searchString;
            if (!string.IsNullOrEmpty(searchString))
            {
                if (int.TryParse(searchString, out int index))
                {
                    List<RegistruTratamente> datetratamente = context.RegistruTratamente.Include(r => r.Parcela).Include(r => r.Angajat).Include(r => r.Daunatori).ThenInclude(r => r.Tratament).Where(a => a.Parcela.Locatie.Contains(searchString) ||
                 a.Angajat.Nume.Contains(searchString) || a.Angajat.Prenume.Contains(searchString) || a.Daunatori.Denumire.Contains(searchString) || a.Daunatori.Tratament.Denumire.Contains(searchString) || a.Suprafata == index).ToList();
                    return View(datetratamente);
                }
                else
                {
                    List<RegistruTratamente> datetratamente = context.RegistruTratamente.Include(r => r.Parcela).Include(r => r.Angajat).Include(r => r.Daunatori).ThenInclude(r => r.Tratament).Where(a => a.Parcela.Locatie.Contains(searchString) ||
                 a.Angajat.Nume.Contains(searchString) || a.Angajat.Prenume.Contains(searchString) || a.Daunatori.Denumire.Contains(searchString) || a.Daunatori.Tratament.Denumire.Contains(searchString)).ToList();
                    return View(datetratamente);
                }
            }
            List<RegistruTratamente> registruTratamente = context.RegistruTratamente.Include(r => r.Parcela).Include(r => r.Angajat).Include(r => r.Daunatori).ThenInclude(r => r.Tratament).ToList();
            return View(registruTratamente);
        }
        [HttpPost]
        public IActionResult Stergere(int[] registruTratamenteId)
        {
            foreach (int Id in registruTratamenteId)
            {
                RegistruTratamente tratament = context.RegistruTratamente.Find(Id);
                context.RegistruTratamente.Remove(tratament);

            }
            context.SaveChanges();
            return Redirect("/RegistruTratamente");
        }
        [HttpGet]
        public IActionResult Editare(int id)
        {
            var tratament = context.RegistruTratamente.Find(id);
            if (tratament == null)
            {
                return NotFound();
            }

            var editRegistruTratamenteViewModel = new AddRegistruTratamenteViewModel
            {
                CodTratamentAplicat = tratament.CodTratamentAplicat,
                CodParcela = tratament.CodParcela,
                CodDaunator = tratament.CodDaunator,
                CodAngajat = tratament.CodAngajat,
                Suprafata = tratament.Suprafata,
                DataAplicare = tratament.DataAplicare
            };
            CheiExterne(editRegistruTratamenteViewModel);

            return View(editRegistruTratamenteViewModel);
        }

        [HttpPost]
        public IActionResult Editare(AddRegistruTratamenteViewModel editRegistruTratamenteViewModel)
        {
            if (ModelState.IsValid)
            {
                var tratament = context.RegistruTratamente.Find(editRegistruTratamenteViewModel.CodTratamentAplicat);
                if (tratament == null)
                {
                    return NotFound();
                }
                tratament.CodParcela = editRegistruTratamenteViewModel.CodParcela;
                tratament.CodDaunator = editRegistruTratamenteViewModel.CodDaunator;
                tratament.Suprafata = editRegistruTratamenteViewModel.Suprafata;
                tratament.CodAngajat = editRegistruTratamenteViewModel.CodAngajat;
                tratament.DataAplicare = editRegistruTratamenteViewModel.DataAplicare;
                context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        private List<T> SortData<T>(List<T> ListaDate, string Ordine)
        {
            if (ListaDate == null || !ListaDate.Any())
            {
                return ListaDate;
            }

            if (string.IsNullOrEmpty(Ordine))
            {
                return ListaDate;
            }

            var descrescator = Ordine.EndsWith("_desc");
            var propNume = descrescator ? Ordine.Substring(0, Ordine.Length - 5) : Ordine;
            
            Func<T, object> keySelector;
            if (propNume == "Parcela")
            {
                keySelector = item => typeof(T).GetProperty("Parcela")?.GetValue(item)?.GetType().GetProperty("CodParcela")?.GetValue(typeof(T).GetProperty("Parcela")?.GetValue(item));
            }
            else
               if (propNume == "Angajat")
            {
                keySelector = item => typeof(T).GetProperty("Angajat")?.GetValue(item)?.GetType().GetProperty("Nume")?.GetValue(typeof(T).GetProperty("Angajat")?.GetValue(item));
            }
            else
               if (propNume == "Daunator")
            {
                keySelector = item => typeof(T).GetProperty("Daunatori")?.GetValue(item)?.GetType().GetProperty("Denumire")?.GetValue(typeof(T).GetProperty("Daunatori")?.GetValue(item));
            }

ProiectLicenta/Views/RegistruTratamente/Adaugare.cshtml
@using ProiectLicenta.ViewModels;
@model AddRegistruTratamenteViewModel;
@{
    ViewData["Title"] = "Adaugare Tratament";
}
<h1 class=" fw-bold pb-2 pb-xl-3 text-center">Adaugare Tratament Aplicat</h1>
<div>
    <a class="btn btn-warning me-3" href="@Url.Action("Index", "RegistruTratamente")"><i class="bi bi-arrow-left"></i> Inapoi</a>
    <div asp-controller="RegistruTratamente" asp-action="Adaugare" class="bd-example">
        <form method="post">
            <div class="mb-3 mt-3">
                <select class="form-select form-control-lg" asp-for="CodParcela" asp-items="ViewBag.codParcela">
                    <option value="0" hidden>Alege Parcela</option>
            </select>
                <span class="text-danger" asp-validation-for="CodParcela"></span>
            </div>
            <div class="mb-3">
                <select class="form-select form-control-lg" asp-for="CodDaunator" asp-items="ViewBag.codDaunator">
                    <option value="0" hidden>Alege Daunator</option>
            </select>
                <span class="text-danger" asp-validation-for="CodDaunator"></span>
            </div>
            <div class=" form-floating mb-3">
                <input id="floatingInput" class="form-control" placeholder="Suprafata" asp-for="Suprafata" />
                <label for="floatingInput" asp-for="Suprafata">Suprafata</label>
                <span class="text-danger" asp-validation-for="Suprafata"></span>
            </div>
            <div class="mb-3">
                <select class="form-select form-control-lg" asp-for="CodAngajat" asp-items="ViewBag.codAngajat">
                    <option value="0" hidden>Alege Angajat</option>
            </select>
                <span class="text-danger" asp-validation-for="CodAngajat"></span>
            </div>
            <div class="form-floating date mb-3">
                <input type="date" id="floatingInput" class="form-control" placeholder="Data Aplicare" asp-for="DataAplicare" />
                <label for="floatingInput" asp-for="DataAplicare">Data Aplicare</label>
                <span class="text-danger" asp-validation-for="DataAplicare"></span>
            </div>
            <div class="mb-3"> <label><input type="checkbox" asp-for="Stare" value="true" /> Sarcina Indeplinita</label></div>

            <input class="btn btn-primary" type="submit" value="Adaugare Tratament Aplicat" />
    </form>
</div>
</div>

ProiectLicenta/Views/RegistruTratamente/Editare.cshtml
@using ProiectLicenta.ViewModels;
@model AddRegistruTratamenteViewModel;
@{
    ViewData["Title"] = "Editare Tratament";
}
<h1 class=" fw-bold pb-2 pb-xl-3 text-center"><i class="bi bi-pencil-fill"></i> Editare Tratament Aplicat</h1>
<div>
    <a class="btn btn-warning me-3" href="@Url.Action("Index", "RegistruTratamente")"><i class="bi bi-arrow-left"></i> Inapoi</a>
    <div asp-controller="RegistruTratamente" asp-action="Editare" class="bd-example">
        <form method="post">
            <div class="mt-3 mb-3">
                <select class="form-select form-control-lg" asp-for="CodParcela" asp-items="ViewBag.codParcela">
                    <option value="0" hidden>Alege Parcela</option>
            </select>
                <span class="text-danger" asp-validation-for="CodParcela"></span>
            </div>
            <div class="mb-3">
                <select class="form-select form-control-lg" asp-for="CodDaunator" asp-items="ViewBag.codDaunator">
                    <option value="0" hidden>Alege Daunator</option>
            </select>
                <span class="text-danger" asp-validation-for="CodDaunator"></span>
            </div>
            <div class=" form-floating mb-3">
                <input id="floatingInput" class="form-control" placeholder="Suprafata" asp-for="Suprafata" />
                <label for="floatingInput" asp-for="Suprafata">Suprafata</label>
                <span class="text-danger" asp-validation-for="Suprafata"></span>
            </div>
            <div class="mb-3">
                <select class="form-select form-control-lg" asp-for="CodAngajat" asp-items="ViewBag.codAngajat">
                    <option value="0" hidden>Alege Angajat</option>
            </select>
                <span class="text-danger" asp-validation-for="CodAngajat"></span>
            </div>
            <div class="form-floating date mb-3">
                <input type="date" id="floatingInput" class="form-control" placeholder="Data Aplicare" asp-for="DataAplicare" />
                <label for="floatingInput" asp-for="DataAplicare">Data Aplicare</label>
                <span class="text-danger" asp-validation-for="DataAplicare"></span>
            </div>
            <div>
                <input type="hidden" asp-for="CodTratamentAplicat" />
            </div>
            <input class="btn btn-primary" type="submit" value="Editare Tratament Aplicat" />
    </form>
</div>
</div>

ProiectLicenta/Views/RegistruTratamente/Index.cshtml
@using ProiectLicenta.Models
@model List<RegistruTratamente>
@{
    ViewData["Title"] = "Registru Tratamente";
    string currentSort = ViewBag.SortOrder != null ? ViewBag.SortOrder : "";
    string filtru = ViewBag.CurrentFilter != null ? ViewBag.CurrentFilter : "";
}
<h1 class=" fw-bold pb-2 pb-xl-3 text-center"><i class="bi bi-journals"></i> Registru Tratamente </h1>
<div class="mb-3">
    <a class="btn btn-warning me-3" href="@Url.Action("Index", "Home")"><i class="bi bi-arrow-left"></i> Inapoi</a>
    <a class="btn btn-primary" asp-controller="RegistruTratamente" asp-action="Adaugare"><i class="bi bi-plus-lg"></i> Adaugare</a>
    <a class="btn btn-danger float-end" asp-controller="RegistruTratamente" asp-action="Stergere"><i class="bi bi-trash3"></i> Stergere</a>
</div>
<div class="mb-3">
    <form class="d-flex" asp-action="Index" method="get">
        <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
        <input class="form-control ms-2" type="search" placeholder="Cautare" aria-label="Cautare" name="searchString" value="@ViewBag.CurrentFilter">
    </form>
</div>
<div class="mb-3">
    <h4 hidden>Date</h4>
    <button class="btn btn-secondary mb-3" onclick="downloadTableAsHtml()"><i class="bi bi-file-earmark-arrow-down"></i> Descarca Continut</button>
</div>
<div>
@if (Model.Count == 0)
{
    <p> Nu exista tratamente aplicate in registru!</p>
}
else
{
        <table class="table table-striped table-bordered" id="registruTable">
            <tr>
                <th colspan="2" class="fit-content">
                    Nr.
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "CodTratamentAplicat" ? "CodTratamentAplicat_desc" : "CodTratamentAplicat",searchString = filtru  })">
                        @if (currentSort != "CodTratamentAplicat_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Parcela
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "Parcela" ? "Parcela_desc" : "Parcela",searchString = filtru  })">
                        @if (currentSort != "Parcela_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Daunatori
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "Daunator" ? "Daunator_desc" : "Daunator",searchString = filtru  })">
                        @if (currentSort != "Daunator_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Tratament
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "Tratament" ? "Tratament_desc" : "Tratament",searchString = filtru  })">
                        @if (currentSort != "Tratament_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Suprafata
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "Suprafata" ? "Suprafata_desc" : "Suprafata",searchString = filtru  })">
                        @if (currentSort != "Suprafata_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Angajat
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "Angajat" ? "Angajat_desc" : "Angajat",searchString = filtru  })">
                        @if (currentSort != "Angajat_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Data Aplicare
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "DataAplicare" ? "DataAplicare_desc" : "DataAplicare",searchString = filtru  })">
                        @if (currentSort != "DataAplicare_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>

            </tr>
        @foreach (var var in Model)
        {
            <tr>
                    <td class="fit-content">
                        <a href="@Url.Action("Editare", "RegistruTratamente", new {id = var.CodTratamentAplicat })"><i class="bi bi-pencil-fill link-primary"></i></a>
                    </td>
                    <td class="fit-content">
                    @var.CodTratamentAplicat
                </td>
                <td>
                    @var.Parcela.CodParcela | @var.Parcela.Locatie
                </td>
                <td>
                    @var.Daunatori.Denumire
                </td>
                <td>
                    @var.Daunatori.Tratament.Denumire
                    </td>
                <td>
                        @var.Suprafata &#x33A1;
                </td>
                <td>
                    @var.Angajat.Nume @var.Angajat.Prenume
                </td>
                <td>
                    @var.DataAplicare.ToString("dd/MM/yyyy")
                </td>
            </tr>
        }

    </table>
}</div>

ProiectLicenta/Views/RegistruTratamente/Stergere.cshtml
@model List<RegistruTratamente>
@{
    ViewData["Title"] = "Stergere Tratament";
}
<h1 class=" fw-bold pb-2 pb-xl-3 text-center"><i class="bi bi-trash3"></i> Sterge Tratament Aplicat</h1>
<a class="btn btn-warning me-3" href="@Url.Action("Index", "RegistruTratamente")"><i class="bi bi-arrow-left"></i> Inapoi</a>
<div class="mb-3 mt-3">
    <form class="d-flex" asp-action="Stergere" method="get">
        <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
        <input class="form-control ms-2" type="search" placeholder="Cautare" aria-label="Cautare" name="searchString" value="@ViewBag.CurrentFilter">
    </form>
</div>
<form method="post">
    <div class="mt-3">
        @if (Model.Count == 0)
        {
            <p>Nu exista Tratamente Aplicate!</p>
        }
        else
        {
            <table class="table table-striped table-bordered">
                <tr>
                    <th colspan="2" class="fit-content">
                        Nr.
                    </th>
                    <th>
                        Parcela
                    </th>
                    <th>
                        Daunator
                    </th>
                    <th>
                        Suprafata
                    </th>
                    <th>
                        Angajat
                    </th>
                    <th>
                        Data Aplicare
                    </th>
                    <th>Sarcina</th>
                </tr> @foreach (var var in Model)
                {
                    <tr>
                        <td>
                            <input type="checkbox" name="registruTratamenteId" value="@var.CodTratamentAplicat" />
                        </td>
                        <td>
                            @var.CodTratamentAplicat
                        </td>
                        <td>
                            @var.Parcela.Locatie
                        </td>
                        <td>
                            @var.Daunatori.Denumire
                        </td>
                        <td>
                            @var.Suprafata
                        </td>
                        <td>
                            @var.Angajat.Nume @var.Angajat.Prenume
                        </td>
                        <td>
                            @var.DataAplicare.ToString("dd/MM/yyyy")
                        </td>
                        <td>
                            @if (var.Stare == false)
                            {
                                <i class="bi bi-three-dots"></i>
                            }
                            else
                            {
                                <i class="bi bi-check-lg"></i>
                            }
                        </td>
                    </tr>
                }
            </table>
        }
    </div>
    <input type="submit" value="Stergere" name="Stergere" class="btn btn-danger" />
</form>