ProiectLicenta/Models/RegistruPalisare.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProiectLicenta.Models
{
    public class RegistruPalisare
    {
        [Key]
        public int CodPalisare { get; set; }
        [ForeignKey("Parcela")]
        public int CodParcela { get; set; }
        [Required]
        public int NumarPlante { get; set; }
        [ForeignKey("Angajat")]
        public int CodAngajat { get; set; }
        [Required]
        public DateTime DataPalisare { get; set; }
        public bool Stare { get; set; }

        public Angajat? Angajat { get; set; }
        public Parcela? Parcela { get; set; }
        public RegistruPalisare(int codPalisare, int codParcela, int numarPlante, int codAngajat, DateTime dataPalisare, bool stare)
        {
            this.CodPalisare = codPalisare;
            this.CodParcela = codParcela;
            this.NumarPlante = numarPlante;
            this.CodAngajat = codAngajat;
            this.DataPalisare = dataPalisare;
            this.Stare = stare;

        }
    }
}

ProiectLicenta/Controllers/RegistruPalisareController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ProiectLicenta.Data;
using ProiectLicenta.Models;
using ProiectLicenta.ViewModels;

namespace ProiectLicenta.Controllers
{[Authorize]
    public class RegistruPalisareController : Controller
    {
        
        private ApplicationDbContext context;
        public RegistruPalisareController(ApplicationDbContext dbcontext)
        {
            this.context = dbcontext;
        }
        public void CheiExterne(AddRegistruPalisareViewModel intrare)
        {
            var codAngajat = context.Angajat.OrderBy(p => p.Nume).ToList();
            ViewBag.codAngajat = codAngajat.Select(p => new SelectListItem
            {
                Value = p.CodAngajat.ToString(),
                Text = p.Nume + " " + p.Prenume,
                Selected = p.CodAngajat == intrare.CodAngajat,
            });
            var codParcela = context.Parcela.OrderBy(p => p.Locatie).ToList();
            ViewBag.codParcela = codParcela.Select(p => new SelectListItem
            {
                Value = p.CodParcela.ToString(),
                Text = p.Locatie,
                Selected = p.CodParcela == intrare.CodParcela,
            });

        }
        [HttpGet]
        public ActionResult Index(string sortOrder,string searchString)
        {
            ViewBag.SortOrder = sortOrder;
            ViewBag.CurrentFilter = searchString;
            if (!string.IsNullOrEmpty(searchString))
            {
                if (int.TryParse(searchString, out int index))
                {
                    List<RegistruPalisare> datePalisare = SortData(context.RegistruPalisare.Include(r => r.Parcela).Include(r => r.Angajat).Where(a => a.Parcela.Locatie.Contains(searchString) && a.Stare == true ||
                 a.Angajat.Nume.Contains(searchString) || a.Angajat.Prenume.Contains(searchString) || a.NumarPlante == index).ToList(), sortOrder);
                    return View(datePalisare);
                }
                else
                {
                    List<RegistruPalisare> datePalisare = SortData(context.RegistruPalisare.Include(r => r.Parcela).Include(r => r.Angajat).Where(a => a.Parcela.Locatie.Contains(searchString) && a.Stare == true ||
                 a.Angajat.Nume.Contains(searchString) || a.Angajat.Prenume.Contains(searchString)).ToList(), sortOrder);
                    return View(datePalisare);
                }
            }
            List<RegistruPalisare> registruPalisare = SortData(context.RegistruPalisare.Include(r => r.Parcela).Include(r => r.Angajat).Where(a => a.Stare == true).ToList(),sortOrder);
            return View(registruPalisare);
        }
        [HttpGet]
        public IActionResult Adaugare()
        {
            AddRegistruPalisareViewModel addRegistruPalisareViewModel = new AddRegistruPalisareViewModel();
            CheiExterne(addRegistruPalisareViewModel);
            addRegistruPalisareViewModel.DataPalisare = DateTime.Today;
            return View(addRegistruPalisareViewModel);
        }
        [HttpPost]
        public IActionResult Adaugare(AddRegistruPalisareViewModel addRegistruPalisareViewModel)
        {
            if (ModelState.IsValid)
            {
                RegistruPalisare newRegistruPalisare = new RegistruPalisare(
                    addRegistruPalisareViewModel.CodPalisare,
                    addRegistruPalisareViewModel.CodParcela,
                    addRegistruPalisareViewModel.NumarPlante,
                    addRegistruPalisareViewModel.CodAngajat,
                    addRegistruPalisareViewModel.DataPalisare,
                    addRegistruPalisareViewModel.Stare

                );

                context.RegistruPalisare.Add(newRegistruPalisare);
                context.SaveChanges();
                return Redirect("/RegistruPalisare");
            }
            return Adaugare();
        }
        public IActionResult Stergere(string searchString)
        {
            ViewBag.CurrentFilter = searchString;
            if (!string.IsNullOrEmpty(searchString))
            {
                if (int.TryParse(searchString, out int index))
                {
                    List<RegistruPalisare> datePalisare = context.RegistruPalisare.Include(r => r.Parcela).Include(r => r.Angajat).Where(a => a.Parcela.Locatie.Contains(searchString) ||
                 a.Angajat.Nume.Contains(searchString) || a.Angajat.Prenume.Contains(searchString) || a.NumarPlante == index).ToList();
                    return View(datePalisare);
                }
                else
                {
                    List<RegistruPalisare> datePalisare = context.RegistruPalisare.Include(r => r.Parcela).Include(r => r.Angajat).Where(a => a.Parcela.Locatie.Contains(searchString) ||
                 a.Angajat.Nume.Contains(searchString) || a.Angajat.Prenume.Contains(searchString)).ToList();
                    return View(datePalisare);
                }
            }
            List<RegistruPalisare> registruPalisare = context.RegistruPalisare.Include(r => r.Parcela).Include(r => r.Angajat).ToList();
            return View(registruPalisare);
        }
        [HttpPost]
        public IActionResult Stergere(int[] registruPalisareId)
        {
            foreach (int Id in registruPalisareId)
            {
                RegistruPalisare registruPalisare = context.RegistruPalisare.Find(Id);
                context.RegistruPalisare.Remove(registruPalisare);

            }
            context.SaveChanges();
            return Redirect("/RegistruPalisare");
        }
        [HttpGet]
        public IActionResult Editare(int id)
        {
            var palisare = context.RegistruPalisare.Find(id);
            if (palisare == null)
            {
                return NotFound();
            }

            var editRegistruPalisareViewModel = new AddRegistruPalisareViewModel
            {
                CodPalisare = palisare.CodPalisare,
                CodParcela = palisare.CodParcela,
                NumarPlante = palisare.NumarPlante,
                CodAngajat = palisare.CodAngajat,
                DataPalisare = palisare.DataPalisare
            };
            CheiExterne(editRegistruPalisareViewModel);

            return View(editRegistruPalisareViewModel);
        }

        [HttpPost]
        public IActionResult Editare(AddRegistruPalisareViewModel editRegistruPalisareViewModel)
        {
            if (ModelState.IsValid)
            {
                var palisare = context.RegistruPalisare.Find(editRegistruPalisareViewModel.CodPalisare);
                if (palisare == null)
                {
                    return NotFound();
                }
                palisare.CodParcela = editRegistruPalisareViewModel.CodParcela;
                palisare.NumarPlante = editRegistruPalisareViewModel.NumarPlante;
                palisare.CodAngajat = editRegistruPalisareViewModel.CodAngajat;
                palisare.DataPalisare = editRegistruPalisareViewModel.DataPalisare;
                context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        private List<T> SortData<T>(List<T> ListaDate, string Ordine)
        {
            if (ListaDate == null || !ListaDate.Any())
            {
                return ListaDate;
            }

            if (string.IsNullOrEmpty(Ordine))
            {
                return ListaDate;
            }

            var descrescator = Ordine.EndsWith("_desc");
            var propNume = descrescator ? Ordine.Substring(0, Ordine.Length - 5) : Ordine;
            Func<T, object> keySelector;

            if (propNume == "Parcela")
            {
                keySelector = item => typeof(T).GetProperty("Parcela")?.GetValue(item)?.GetType().GetProperty("CodParcela")?.GetValue(typeof(T).GetProperty("Parcela")?.GetValue(item));
            }
            else
               if (propNume == "Angajat")
            {
                keySelector = item => typeof(T).GetProperty("Angajat")?.GetValue(item)?.GetType().GetProperty("Nume")?.GetValue(typeof(T).GetProperty("Angajat")?.GetValue(item));
            }
            else
            {
                var propInfo = typeof(T).GetProperty(propNume);
                if (propInfo == null)
                {
                    return ListaDate;
                }
                keySelector = item => propInfo.GetValue(item);
            }
            if (descrescator)
            {
                ListaDate = ListaDate.OrderByDescending(keySelector).ToList();
            }
            else
            {
                ListaDate = ListaDate.OrderBy(keySelector).ToList();
            }
            return ListaDate;
        }
    }
}

ProiectLicenta/Views/RegistruPalisare/Adaugare.cshtml
@using ProiectLicenta.ViewModels;
@model AddRegistruPalisareViewModel;
@{
    ViewData["Title"] = "Adaugare Palisare";
}
<h1 class ="  fw-bold pb-2 pb-xl-3 text-center">Adaugare Palisare</h1>
<div>
    <a class="btn btn-warning me-3" href="@Url.Action("Index", "RegistruPalisare")"><i class="bi bi-arrow-left"></i> Inapoi</a>
    <div asp-controller="RegistruPalisare" asp-action="Adaugare" class="bd-example">
        <form method="post">
            <div class="mb-3 mt-3">
                <select class="form-select form-control-lg" asp-for="CodParcela" asp-items="ViewBag.codParcela">
                    <option value="0" hidden>Alege Parcela</option>
            </select>
                <span class="text-danger" asp-validation-for="CodParcela"></span>
            </div>
            <div class=" form-floating mb-3">
                <input id="floatingInput" class="form-control" placeholder="Numar Plante" asp-for="NumarPlante" />
                <label for="floatingInput" asp-for="NumarPlante">Numar Plante</label>
                <span class="text-danger" asp-validation-for="NumarPlante"></span>
            </div>
            <div class="mb-3">
                <select class="form-select form-control-lg" asp-for="CodAngajat" asp-items="ViewBag.codAngajat">
                    <option value="0" hidden>Alege Angajat</option>
            </select>
                <span class="text-danger" asp-validation-for="CodAngajat"></span>
            </div>
            <div class="form-floating date mb-3">
                <input type="date" id="floatingInput" class="form-control" placeholder="Data Palisare" asp-for="DataPalisare" />
                <label for="floatingInput"  asp-for="DataPalisare">Data Palisare</label>
                <span class="text-danger" asp-validation-for="DataPalisare"></span>
            </div>
            <div class="mb-3"> <label><input type="checkbox" asp-for="Stare" value="true" /> Sarcina Indeplinita</label></div>

            <input class="btn btn-primary" type="submit" value="Adaugare Palisare" />
    </form>
</div>
</div>

ProiectLicenta/Views/RegistruPalisare/Editare.cshtml
@using ProiectLicenta.ViewModels;
@model AddRegistruPalisareViewModel;
@{
    ViewData["Title"] = "Editare Palisare";
}
<h1 class="  fw-bold pb-2 pb-xl-3 text-center"><i class="bi bi-pencil-fill"></i> Editare Palisare</h1>
<div>
    <a class="btn btn-warning me-3" href="@Url.Action("Index", "RegistruPalisare")"><i class="bi bi-arrow-left"></i> Inapoi</a>
    <div asp-controller="RegistruPalisare" asp-action="Editare" class="bd-example">
        <form method="post">
            <div class="mb-3 mt-3">
                <select class="form-select form-control-lg" asp-for="CodParcela" asp-items="ViewBag.codParcela">
                    <option value="0" hidden>Alege Parcela</option>
            </select>
                <span class="text-danger" asp-validation-for="CodParcela"></span>
            </div>
            <div class=" form-floating mb-3">
                <input id="floatingInput" class="form-control" placeholder="Numar Plante" asp-for="NumarPlante" />
                <label for="floatingInput" asp-for="NumarPlante">Numar Plante</label>
                <span class="text-danger" asp-validation-for="NumarPlante"></span>
            </div>
            <div class="mb-3">
                <select class="form-select form-control-lg" asp-for="CodAngajat" asp-items="ViewBag.codAngajat">
                    <option value="0" hidden>Alege Angajat</option>
            </select>
                <span class="text-danger" asp-validation-for="CodAngajat"></span>
            </div>
            <div class="form-floating date mb-3">
                <input type="date" id="floatingInput" class="form-control" placeholder="Data Palisare" asp-for="DataPalisare" />
                <label for="floatingInput"  asp-for="DataPalisare">Data Palisare</label>
                <span class="text-danger" asp-validation-for="DataPalisare"></span>
            </div>
            <div>
                <input type="hidden" asp-for="CodPalisare" />
            </div>
            <input class="btn btn-primary" type="submit" value="Editare Palisare" />
    </form>
</div>
</div>

ProiectLicenta/Views/RegistruPalisare/Index.cshtml
@using ProiectLicenta.Models
@model List<RegistruPalisare>
@{ViewData["Title"] = "Registru Palisare";
    string currentSort = ViewBag.SortOrder != null ? ViewBag.SortOrder : "";
    string filtru = ViewBag.CurrentFilter != null ? ViewBag.CurrentFilter : "";
}
<h1 class="  fw-bold pb-2 pb-xl-3 text-center"><i class="bi bi-journals"></i> Registru Palisare </h1>
<div class="mb-3">
    <a class="btn btn-warning me-3" href="@Url.Action("Index", "Home")"><i class="bi bi-arrow-left"></i> Inapoi</a>
    <a class="btn btn-primary" asp-controller="RegistruPalisare" asp-action="Adaugare"><i class="bi bi-plus-lg"></i> Adaugare</a>
    <a class="btn btn-danger float-end" asp-controller="RegistruPalisare" asp-action="Stergere"><i class="bi bi-trash3"></i> Stergere</a>
</div>
<div class="mb-3">
    <form class="d-flex" asp-action="Index" method="get">
        <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
        <input class="form-control ms-2" type="search" placeholder="Cautare" aria-label="Cautare" name="searchString" value="@ViewBag.CurrentFilter">
    </form>
</div>
<div class="mb-3">
    <h4 hidden>Date</h4>
    <button class="btn btn-secondary mb-3" onclick="downloadTableAsHtml()"><i class="bi bi-file-earmark-arrow-down"></i> Descarca Continut</button>
</div>
<div>
@if (Model.Count == 0)
{
    <p> Nu exista palisari in registru!</p>
}
else
{
        <table class="table table-striped table-bordered" id="registruTable">
            <tr>
                <th colspan="2" class="fit-content">
                    Nr.
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "CodPalisare" ? "CodPalisare_desc" : "CodPalisare",searchString = filtru })">
                        @if (currentSort != "CodPalisare_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Parcela
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "Parcela" ? "Parcela_desc" : "Parcela",searchString = filtru })">
                        @if (currentSort != "Parcela_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Numar Plante
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "NumarPlante" ? "NumarPlante_desc" : "NumarPlante",searchString = filtru })">
                        @if (currentSort != "NumarPlante_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Angajat
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "Angajat" ? "Angajat_desc" : "Angajat",searchString = filtru })">
                        @if (currentSort != "Angajat_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Data Palisare
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "DataPalisare" ? "DataPalisare_desc" : "DataPalisare",searchString = filtru })">
                        @if (currentSort != "DataPalisare_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
            </tr>
        @foreach (var var in Model)
        {
            <tr>
                    <td class="fit-content">
                        <a href="@Url.Action("Editare", "RegistruPalisare", new {id = var.CodPalisare })"><i class="bi bi-pencil-fill link-primary"></i></a>
                    </td>
                    <td class="fit-content">
                    @var.CodPalisare
                </td>
                <td>
                    @var.Parcela.CodParcela - @var.Parcela.Locatie
                    
                </td>
                <td>
                    @var.NumarPlante
                </td>
                <td>
                    @var.Angajat.Nume @var.Angajat.Prenume
                </td>
                <td>
                        @var.DataPalisare.ToString("dd/MM/yyyy")
                    </td>
            </tr>
        }

    </table>
}</div>

ProiectLicenta/Views/RegistruPalisare/Stergere.cshtml
@model List<RegistruPalisare>
@{
    ViewData["Title"] = "Stergere Palisare";
}
<h1 class="  fw-bold pb-2 pb-xl-3 text-center"><i class="bi bi-trash3"></i> Sterge Palisare</h1>
<a class="btn btn-warning me-3" href="@Url.Action("Index", "RegistruPalisare")"><i class="bi bi-arrow-left"></i> Inapoi</a>
<div class="mb-3 mt-3">
    <form class="d-flex" asp-action="Stergere" method="get">
        <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
        <input class="form-control ms-2" type="search" placeholder="Cautare" aria-label="Cautare" name="searchString" value="@ViewBag.CurrentFilter">
    </form>
</div>
<form method="post">
    <div class="mt-3">
        @if (Model.Count == 0)
        {
            <p>Nu exista Palisari!</p>
        }
        else
        {
            <table class="table table-striped table-bordered">
                <tr>
                    <th colspan="2" class="fit-content">
                        Nr.
                    </th>
                    <th>
                        Parcela
                    </th>
                    <th>
                        Numar Plante
                    </th>
                    <th>
                        Angajat
                    </th>
                    <th>
                        Data Palisare
                    </th>
                    <th>Sarcina</th>
                </tr>
                @foreach (var var in Model)
                {
                    <tr>
                        <td>
                            <input type="checkbox" name="registruPalisareId" value="@var.CodPalisare" />
                        </td>
                        <td>
                            @var.CodPalisare
                        </td>
                        <td>
                            @var.Parcela.Locatie

                        </td>
                        <td>
                            @var.NumarPlante
                        </td>
                        <td>
                            @var.Angajat.Nume @var.Angajat.Prenume
                        </td>
                        <td>
                            @var.DataPalisare.ToString("dd/MM/yyyy")
                        </td>
                        <td>@if (var.Stare == false)
                            {
                                <i class="bi bi-three-dots"></i>
                            }
                            else
                            {
                                <i class="bi bi-check-lg"></i>
                            }
                        </td>
                    </tr>
                }
            </table>
        }
    </div>
    <input value="Stergere" type="submit" name="Stergere" class="btn btn-danger" />
</form>