ProiectLicenta/Controllers/ParceleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ProiectLicenta.Data;
using ProiectLicenta.Models;
using ProiectLicenta.ViewModels;
namespace ProiectLicenta.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ParceleController : Controller
    {
        private readonly ApplicationDbContext context;
        public ParceleController(ApplicationDbContext dbcontext)
        {
            this.context = dbcontext;
        }
        [HttpGet]
        public ActionResult Index(string sortOrder,string searchString)
        {
            ViewBag.SortOrder = sortOrder;
            ViewBag.CurrentFilter = searchString;
            if (!string.IsNullOrEmpty(searchString))
            {if (int.TryParse(searchString, out int index))
                {
                    List<Parcela> dateParcela = SortData(context.Parcela.Include(r => r.Rasaduri).Where(a => a.Locatie.Contains(searchString) || a.Tip.Contains(searchString) ||
                    a.Rasaduri.Denumire.Contains(searchString) || a.Rasaduri.Planta.Contains(searchString) || a.NumarPlante == index || a.Suprafata == index).ToList(), sortOrder);
                    return View(dateParcela);
                }
                else
                {
                    List<Parcela> dateParcela = SortData(context.Parcela.Include(r => r.Rasaduri).Where(a => a.Locatie.Contains(searchString) || a.Tip.Contains(searchString) ||
                    a.Rasaduri.Denumire.Contains(searchString) || a.Rasaduri.Planta.Contains(searchString)).ToList(), sortOrder);
                    return View(dateParcela);
                }
            }
            List<Parcela> parcela = SortData(context.Parcela.Include(r => r.Rasaduri).ToList(), sortOrder);
            return View(parcela);
        }
        public void CheiExterne(AddParcelaViewModel intrare)
        {
            var codRasad = context.Rasad.Where(p=>p.Cantitate!=0).OrderBy(p => p.Denumire).ToList();
            ViewBag.codRasad = codRasad.Select(p => new SelectListItem
            {
                Value = p.CodRasad.ToString(),
                Text = p.Planta + "-" +p.Denumire + "-" +p.Cantitate + "Buc",
                Selected = p.CodRasad == intrare.CodRasad,
            });
        }
        [HttpGet]
        public IActionResult Adaugare()
        {
            AddParcelaViewModel addParcelaViewModel = new AddParcelaViewModel();
            CheiExterne(addParcelaViewModel);
            return View(addParcelaViewModel);
        }
        [HttpPost]
        public IActionResult Adaugare(AddParcelaViewModel addParcelaViewModel)
        {
            if (ModelState.IsValid)
            {
                var selectedRasaduri = context.Rasad.Find(addParcelaViewModel.CodRasad);
                if (selectedRasaduri != null && selectedRasaduri.Cantitate >= addParcelaViewModel.NumarPlante)
                {
                    selectedRasaduri.Cantitate -= addParcelaViewModel.NumarPlante;
                    Parcela newParcela = new Parcela(
                     addParcelaViewModel.CodParcela,
                     addParcelaViewModel.Locatie,
                     addParcelaViewModel.Tip,
                     addParcelaViewModel.Suprafata,
                     addParcelaViewModel.CodRasad,
                     addParcelaViewModel.NumarPlante
                    );
                    context.Parcela.Add(newParcela);
                    context.SaveChanges();
                    return Redirect("/Parcele");
                }
                else
                {
                   
                    ModelState.AddModelError(string.Empty, "Numarul de plante este prea mare!");
                }
            }
            CheiExterne(addParcelaViewModel);
            return View(addParcelaViewModel);
        }
        public IActionResult Stergere(string searchString)
        {
            ViewBag.CurrentFilter = searchString;
            if (!string.IsNullOrEmpty(searchString))
            {
                if (int.TryParse(searchString, out int index))
                {
                    List<Parcela> dateParcela = context.Parcela.Include(r => r.Rasaduri).Where(a => a.Locatie.Contains(searchString) || a.Tip.Contains(searchString) ||
                    a.Rasaduri.Denumire.Contains(searchString) || a.Rasaduri.Planta.Contains(searchString) || a.NumarPlante == index || a.Suprafata == index).ToList();
                    return View(dateParcela);
                }
                else
                {
                    List<Parcela> dateParcela = context.Parcela.Include(r => r.Rasaduri).Where(a => a.Locatie.Contains(searchString) || a.Tip.Contains(searchString) ||
                    a.Rasaduri.Denumire.Contains(searchString) || a.Rasaduri.Planta.Contains(searchString)).ToList();
                    return View(dateParcela);
                }
            }
            List<Parcela> parcela = context.Parcela.Include(r => r.Rasaduri).ToList();
            return View(parcela);
        }
        [HttpPost]
        public IActionResult Stergere(int[] parcelaId)
        {
            foreach (int Id in parcelaId)
            {
                Parcela parcela = context.Parcela.Find(Id);
                context.Parcela.Remove(parcela);
            }
            context.SaveChanges();
            return Redirect("/Parcele");
        }
        [HttpGet]
        public IActionResult Editare(int id)
        {
            var parcela = context.Parcela.Find(id);
            if (parcela == null)
            {
                return NotFound();
            }

            var editParcelaViewModel = new AddParcelaViewModel
            {   
                CodParcela = parcela.CodParcela,
                Locatie = parcela.Locatie,
                Tip = parcela.Tip,
                CodRasad = parcela.CodRasad,
                NumarPlante= parcela.NumarPlante,
                Suprafata = parcela.Suprafata
            };
            CheiExterne(editParcelaViewModel);

            return View(editParcelaViewModel);
        }

        [HttpPost]
        public IActionResult Editare(AddParcelaViewModel editParcelaViewModel)
        {
            CheiExterne(editParcelaViewModel);
            if (ModelState.IsValid)
            {
                var parcela = context.Parcela.Find(editParcelaViewModel.CodParcela);
                var selectedRasaduri = context.Rasad.Find(editParcelaViewModel.CodRasad);
                parcela.Locatie = editParcelaViewModel.Locatie;
                parcela.Tip = editParcelaViewModel.Tip;
                parcela.CodRasad = editParcelaViewModel.CodRasad;
                parcela.Suprafata = editParcelaViewModel.Suprafata;
                if (selectedRasaduri != null && parcela.NumarPlante < editParcelaViewModel.NumarPlante)
                {
                    if (selectedRasaduri.Cantitate >= editParcelaViewModel.NumarPlante- parcela.NumarPlante)
                    {
                        selectedRasaduri.Cantitate -= editParcelaViewModel.NumarPlante - parcela.NumarPlante;
                        parcela.NumarPlante = editParcelaViewModel.NumarPlante;
                        context.SaveChanges();
                        return Redirect("/Parcele");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Numarul de plante este prea mare!");
                    }
                }
                else 
                if (selectedRasaduri != null && parcela.NumarPlante >= editParcelaViewModel.NumarPlante)
                {
                    selectedRasaduri.Cantitate += parcela.NumarPlante - editParcelaViewModel.NumarPlante;
                    parcela.NumarPlante = editParcelaViewModel.NumarPlante;
                    context.SaveChanges();
                    return Redirect("/Parcele");
                }
            }
            return View(editParcelaViewModel);
        }
        private List<T> SortData<T>(List<T> ListaDate, string Ordine)
        {
            if (ListaDate == null || !ListaDate.Any())
            {
                return ListaDate;
            }

            if (string.IsNullOrEmpty(Ordine))
            {
                return ListaDate;
            }

            var descrescator = Ordine.EndsWith("_desc");
            var propNume = descrescator ? Ordine.Substring(0, Ordine.Length - 5) : Ordine;
            Func<T, object> keySelector;

            if (propNume == "Rasaduri")
            {
                keySelector = item => typeof(T).GetProperty("Rasaduri")?.GetValue(item)?.GetType().GetProperty("Planta")?.GetValue(typeof(T).GetProperty("Rasaduri")?.GetValue(item));
            }
            else
            {
                var propInfo = typeof(T).GetProperty(propNume);
                if (propInfo == null)
                {
                    return ListaDate;
                }
                keySelector = item => propInfo.GetValue(item);
            }

            if (descrescator)
            {
                ListaDate = ListaDate.OrderByDescending(keySelector).ToList();
            }
            else
            {
                ListaDate = ListaDate.OrderBy(keySelector).ToList();
            }
            return ListaDate;
        }
    }
}

ProiectLicenta/Views/Parcele/Adaugare.cshtml
@using ProiectLicenta.ViewModels;
@model AddParcelaViewModel;
@{
    ViewData["Title"] = "Adaugare Parcele";
}

<h1 class="  fw-bold pb-2 pb-xl-3 text-center">Adaugare Parcele</h1>
<div>
    <a class="btn btn-warning me-3" href="@Url.Action("Index", "Parcele")"><i class="bi bi-arrow-left"></i> Inapoi</a>
    <div asp-controller="Parcele" asp-action="Adaugare" class="bd-example">
    <form method="post">
        <div class=" form-floating mt-3 mb-3">
                <input id="floatingInput" class="form-control" placeholder="Locatie" asp-for="Locatie" />
                <label for="floatingInput" asp-for="Locatie">Locatie</label>
                <span class="text-danger" asp-validation-for="Locatie"></span>
            </div>
            <div class=" form-floating mb-3">
                <input id="floatingInput" class="form-control" placeholder="Tip" asp-for="Tip" />
                <label for="floatingInput" asp-for="Tip">Tip</label>

                <span class="text-danger" asp-validation-for="Tip"></span>
            </div>
            <div class=" form-floating mb-3">
                <input id="floatingInput" class="form-control" placeholder="Suprafata (mp)" asp-for="Suprafata" />
                <label for="floatingInput" asp-for="Suprafata">Suprafata (mp)</label>

                <span class="text-danger" asp-validation-for="Suprafata"></span>
            </div>
            <div class="form-group">
                
                <select class="form-select form-control-lg" asp-for="CodRasad" asp-items="ViewBag.codRasad">
                    <option value="0" hidden>Alege Rasad</option>
                </select>
                <span class="text-danger" asp-validation-for="CodRasad"></span>
            </br>
            </div>
            <div class=" form-floating mb-3">
                <input  id="floatingInput" class="form-control" placeholder="Numar Plante" asp-for="NumarPlante" />
                <label for="floatingInput" asp-for="NumarPlante">Numar Plante</label>
                <span class="text-danger" asp-validation-for="NumarPlante"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger unstyled-list">
            </div>
            <input class="btn btn-primary" type="submit" value="Adaugare Parcela" />
    </form>
    </div>
</div>

ProiectLicenta/Views/Parcele/Editare.cshtml
@using ProiectLicenta.ViewModels;
@model AddParcelaViewModel;
@{
    ViewData["Title"] = "Editare Parcele";
}

<h1 class="  fw-bold pb-2 pb-xl-3 text-center"><i class="bi bi-pencil-fill"></i> Editare Parcele</h1>
<div>
    <a class="btn btn-warning me-3" href="@Url.Action("Index", "Parcele")"><i class="bi bi-arrow-left"></i> Inapoi</a>
    <div asp-controller="Parcele" asp-action="Editare" class="bd-example">
    <form method="post">
        <div class=" form-floating mt-3 mb-3">
                <input id="floatingInput" class="form-control" placeholder="Locatie" asp-for="Locatie" />
                <label for="floatingInput" asp-for="Locatie">Locatie</label>
                <span class="text-danger" asp-validation-for="Locatie"></span>
            </div>
            <div class=" form-floating mb-3">
                <input id="floatingInput" class="form-control" placeholder="Tip" asp-for="Tip" />
                <label for="floatingInput" asp-for="Tip">Tip</label>

                <span class="text-danger" asp-validation-for="Tip"></span>
            </div>
            <div class=" form-floating mb-3">
                <input id="floatingInput" class="form-control" placeholder="Suprafata (mp)" asp-for="Suprafata" />
                <label for="floatingInput" asp-for="Suprafata">Suprafata (mp)</label>

                <span class="text-danger" asp-validation-for="Suprafata"></span>
            </div>
            <div class="form-group">
                
                <select class="form-select form-control-lg" asp-for="CodRasad" asp-items="ViewBag.codRasad">
                    <option value="0" hidden>Alege Rasad</option>
                </select>
                <span class="text-danger" asp-validation-for="CodRasad"></span>
            </br>
            </div>
            <div class=" form-floating mb-3">
                <input  id="floatingInput" class="form-control" placeholder="Numar Plante" asp-for="NumarPlante" />
                <label for="floatingInput" asp-for="NumarPlante">Numar Plante</label>
                <span class="text-danger" asp-validation-for="NumarPlante"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger unstyled-list">
            </div>
            <div>
                <input type="hidden" asp-for="CodParcela" />
            </div>
            <input class="btn btn-primary" type="submit" value="Editare Parcela" />
    </form>
    </div>
</div>

ProiectLicenta/Views/Parcele/Index.cshtml
@using ProiectLicenta.Models
@model List<Parcela>
@{
    ViewData["Title"] = "Parcele";
    string currentSort = ViewBag.SortOrder != null ? ViewBag.SortOrder : "";
    string filtru = ViewBag.CurrentFilter != null ? ViewBag.CurrentFilter : "";
}
<h1 class="  fw-bold pb-2 pb-xl-3 text-center"><i class="bi bi-layout-wtf"></i> Parcele </h1>
<div class="mb-3">
    <a class="btn btn-warning me-3" href="@Url.Action("Index", "Home")"><i class="bi bi-arrow-left"></i> Inapoi</a>
    <a class="btn btn-primary" asp-controller="Parcele" asp-action="Adaugare"><i class="bi bi-plus-lg"></i> Adaugare</a>
    <a class="btn btn-danger float-end" asp-controller="Parcele" asp-action="Stergere"><i class="bi bi-trash3"></i> Stergere</a>
</div>
<div class="mb-3">
    <form class="d-flex" asp-action="Index" method="get">
        <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
        <input class="form-control ms-2" type="search" placeholder="Cautare" aria-label="Cautare" name="searchString" value="@ViewBag.CurrentFilter">
    </form>
</div>
<div class="mb-3">
    <h4 hidden>Date</h4>
    <button class="btn btn-secondary mb-3" onclick="downloadTableAsHtml()"><i class="bi bi-file-earmark-arrow-down"></i> Descarca Continut</button>
</div>
<div>
@if (Model.Count == 0)
{
    <p> Nu exista parcele!</p>
}
else
{
        <table class="table table-striped table-bordered" id="registruTable">
        <tr>
                <th colspan="2" class="fit-content">
                    Nr.
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "CodParcela" ? "CodParcela_desc" : "CodParcela",searchString = filtru  })">
                        @if (currentSort != "CodParcela_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Locatie
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "Locatie" ? "Locatie_desc" : "Locatie",searchString = filtru })">
                        @if (currentSort != "Locatie_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Tipul
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "Tip" ? "Tip_desc" : "Tip",searchString = filtru })">
                        @if (currentSort != "Tip_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Suprafata
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "Suprafata" ? "Suprafata_desc" : "Suprafata",searchString = filtru })">
                        @if (currentSort != "Suprafata_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Planta
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "Rasaduri" ? "Rasaduri_desc" : "Rasaduri",searchString = filtru })">
                        @if (currentSort != "Rasaduri_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Numar Plante
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "NumarPlante" ? "NumarPlante_desc" : "NumarPlante",searchString = filtru })">
                        @if (currentSort != "NumarPlante_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
        </tr>
        @foreach (var var in Model)
        {
                <tr>
                    <td class="fit-content">
                        <a href="@Url.Action("Editare", "Parcele", new {id = var.CodParcela })"><i class="bi bi-pencil-fill link-primary"></i></a>
                    </td>
                    <td class ="fit-content">
                    @var.CodParcela
                </td>
                <td>
                    @var.Locatie
                </td>
                <td>
                    @var.Tip
                </td>
                <td>
                        @var.Suprafata &#x33A1;
                </td>
                <td>
                        @var.Rasaduri.Planta - @var.Rasaduri.Denumire
                </td>
                <td>
                    @var.NumarPlante
                </td>

            </tr>
        }

    </table>
}</div>

ProiectLicenta/Views/Parcele/Stergere.cshtml
@model List<Parcela>
@{
    ViewData["Title"] = "Stergere Parcele";
}
<h1 class="  fw-bold pb-2 pb-xl-3 text-center"><i class="bi bi-trash3"></i> Sterge Parcele</h1>
<a class="btn btn-warning me-3" href="@Url.Action("Index", "Parcele")"><i class="bi bi-arrow-left"></i> Inapoi</a>
<div class="mb-3 mt-3">
    <form class="d-flex" asp-action="Stergere" method="get">
        <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
        <input class="form-control ms-2" type="search" placeholder="Cautare" aria-label="Cautare" name="searchString" value="@ViewBag.CurrentFilter">
    </form>
</div>
<form method="post">
    <div class="mt-3">
        @if (Model.Count == 0)
        {
            <p>Nu exista Parcele!</p>
        }
        else
        {
            <table class="table table-striped table-bordered">
                <tr>
                    <th colspan="2" class="fit-content">
                        Nr.
                    </th>
                    <th>
                        Locatie
                    </th>
                    <th>
                        Tipul
                    </th>
                    <th>
                        Suprafata
                    </th>
                    <th>
                        Planta
                    </th>
                    <th>
                        Numar de Plante
                    </th>
                </tr>
                @foreach (var var in Model)
                {
                    <tr>
                        <td><input type="checkbox" name="parcelaId" value="@var.CodParcela" /></td>
                        <td>
                            @var.CodParcela
                        </td>
                        <td>
                            @var.Locatie
                        </td>
                        <td>
                            @var.Tip
                        </td>
                        <td>
                            @var.Suprafata
                        </td>
                        <td>
                            @var.Rasaduri.Planta - @var.Rasaduri.Denumire
                        </td>
                        <td>
                            @var.NumarPlante
                        </td>
                    </tr>
                }
            </table>
        }
    </div>
    <input type="submit" value="Stergere" name="Stergere" class="btn btn-danger" />
</form>