ProiectLicenta/Models/RegistruFertilizare.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProiectLicenta.Models
{
    public class RegistruFertilizare
    {
        [Key]
        public int CodFertilizare { get; set; }
        [ForeignKey("Parcela")]
        public int CodParcela { get; set; }
        [Required]
        public int Suprafata { get; set; }
        [ForeignKey("Angajat")]
        public int CodAngajat { get; set; }
        [Required]
        public DateTime DataFertilizare { get; set; }
        public bool Stare { get; set; }

        public Angajat? Angajat { get; set; }
        public Parcela? Parcela { get; set; }
        

        public RegistruFertilizare(int codFertilizare, int codParcela, int suprafata, int codAngajat, DateTime dataFertilizare, bool stare)
        {
            this.CodFertilizare = codFertilizare;
            this.CodParcela = codParcela;
            this.Suprafata = suprafata;
            this.CodAngajat = codAngajat;
            this.DataFertilizare = dataFertilizare;
            this.Stare = stare;

        }

    }
}

ProiectLicenta/Controllers/RegistruFertilizareController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using ProiectLicenta.Data;
using ProiectLicenta.Models;
using ProiectLicenta.ViewModels;

namespace ProiectLicenta.Controllers
{[Authorize]
    public class RegistruFertilizareController : Controller
    {
        
        private ApplicationDbContext context;
        public RegistruFertilizareController(ApplicationDbContext dbcontext)
        {
            this.context = dbcontext;
        }
        [HttpGet]
        public ActionResult Index(string sortOrder,string searchString)
        {
            ViewBag.SortOrder = sortOrder;
            ViewBag.CurrentFilter = searchString;
            if (!string.IsNullOrEmpty(searchString))
            {
                if (int.TryParse(searchString, out int index))
                {
                    List<RegistruFertilizare> dateFertilizare = SortData(context.RegistruFertilizare.Include(r => r.Parcela).Include(r => r.Angajat).Where(a => a.Parcela.Locatie.Contains(searchString) && a.Stare == true ||
                 a.Angajat.Nume.Contains(searchString) || a.Angajat.Prenume.Contains(searchString) || a.Suprafata == index).ToList(), sortOrder);
                    return View(dateFertilizare);
                }
                else
                {
                    List<RegistruFertilizare> dateFertilizare = SortData(context.RegistruFertilizare.Include(r => r.Parcela).Include(r => r.Angajat).Where(a => a.Parcela.Locatie.Contains(searchString) && a.Stare == true ||
                 a.Angajat.Nume.Contains(searchString) || a.Angajat.Prenume.Contains(searchString)).ToList(), sortOrder);
                    return View(dateFertilizare);
                }
            }
            List<RegistruFertilizare> registruFertilizare = SortData(context.RegistruFertilizare.Include(r => r.Parcela).Include(r => r.Angajat).Where(a => a.Stare == true).ToList(),sortOrder);
            return View(registruFertilizare);
        }
        public void CheiExterne(AddRegistruFertilizareViewModel intrare)
        {
            var codAngajat = context.Angajat.OrderBy(p => p.Nume).ToList();
            ViewBag.codAngajat = codAngajat.Select(p => new SelectListItem
            {
                Value = p.CodAngajat.ToString(),
                Text = p.Nume + " " + p.Prenume,
                Selected = p.CodAngajat == intrare.CodAngajat,
            });
            var codParcela = context.Parcela.OrderBy(p => p.Locatie).ToList();
            ViewBag.codParcela = codParcela.Select(p => new SelectListItem
            {
                Value = p.CodParcela.ToString(),
                Text = p.Locatie,
                Selected = p.CodParcela == intrare.CodParcela,
            });

        }
        [HttpGet]
        public IActionResult Adaugare()
        {
            AddRegistruFertilizareViewModel addRegistruFertilizareViewModel = new AddRegistruFertilizareViewModel();
            CheiExterne(addRegistruFertilizareViewModel);
            addRegistruFertilizareViewModel.DataFertilizare = DateTime.Today;
            return View(addRegistruFertilizareViewModel);
        }
        [HttpPost]
        public IActionResult Adaugare(AddRegistruFertilizareViewModel addRegistruFertilizareViewModel)
        {
            if (ModelState.IsValid)
            {
                RegistruFertilizare newRegistruFertilizare = new RegistruFertilizare(
                    addRegistruFertilizareViewModel.CodFertilizare,
                    addRegistruFertilizareViewModel.CodParcela,
                    addRegistruFertilizareViewModel.Suprafata,
                    addRegistruFertilizareViewModel.CodAngajat,
                    addRegistruFertilizareViewModel.DataFertilizare,
                    addRegistruFertilizareViewModel.Stare
                );

                context.RegistruFertilizare.Add(newRegistruFertilizare);
                context.SaveChanges();
                return Redirect("/RegistruFertilizare");
            }
            return Adaugare();
        }
        public IActionResult Stergere(string searchString)
        {
            ViewBag.CurrentFilter = searchString;
            if (!string.IsNullOrEmpty(searchString))
            {
                if (int.TryParse(searchString, out int index))
                {
                    List<RegistruFertilizare> dateFertilizare = context.RegistruFertilizare.Include(r => r.Parcela).Include(r => r.Angajat).Where(a => a.Parcela.Locatie.Contains(searchString) ||
                 a.Angajat.Nume.Contains(searchString) || a.Angajat.Prenume.Contains(searchString) || a.Suprafata == index).ToList();
                    return View(dateFertilizare);
                }
                else
                {
                    List<RegistruFertilizare> dateFertilizare = context.RegistruFertilizare.Include(r => r.Parcela).Include(r => r.Angajat).Where(a => a.Parcela.Locatie.Contains(searchString) ||
                 a.Angajat.Nume.Contains(searchString) || a.Angajat.Prenume.Contains(searchString)).ToList();
                    return View(dateFertilizare);
                }
            }
            List<RegistruFertilizare> registruFertilizare = context.RegistruFertilizare.Include(r => r.Parcela).Include(r => r.Angajat).ToList();
            return View(registruFertilizare);
        }
        [HttpPost]
        public IActionResult Stergere(int[] registruFertilizareId)
        {
            foreach (int Id in registruFertilizareId)
            {
                RegistruFertilizare registruFertilizare = context.RegistruFertilizare.Find(Id);
                context.RegistruFertilizare.Remove(registruFertilizare);

            }
            context.SaveChanges();
            return Redirect("/RegistruFertilizare");
        }
        [HttpGet]
        public IActionResult Editare(int id)
        {
            var fertilizare = context.RegistruFertilizare.Find(id);
            if (fertilizare == null)
            {
                return NotFound();
            }

            var editRegistruFertilizareViewModel = new AddRegistruFertilizareViewModel
            {
                CodFertilizare = fertilizare.CodFertilizare,
                CodParcela = fertilizare.CodParcela,
                Suprafata = fertilizare.Suprafata,
                CodAngajat = fertilizare.CodAngajat,
                DataFertilizare = fertilizare.DataFertilizare
            };
            CheiExterne(editRegistruFertilizareViewModel);

            return View(editRegistruFertilizareViewModel);
        }

        [HttpPost]
        public IActionResult Editare(AddRegistruFertilizareViewModel editRegistruFertilizareViewModel)
        {
            if (ModelState.IsValid)
            {
                var fertilizare = context.RegistruFertilizare.Find(editRegistruFertilizareViewModel.CodFertilizare);
                if (fertilizare == null)
                {
                    return NotFound();
                }
                fertilizare.CodParcela = editRegistruFertilizareViewModel.CodParcela;
                fertilizare.Suprafata = editRegistruFertilizareViewModel.Suprafata;
                fertilizare.CodAngajat = editRegistruFertilizareViewModel.CodAngajat;
                fertilizare.DataFertilizare = editRegistruFertilizareViewModel.DataFertilizare;
                context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        private List<T> SortData<T>(List<T> ListaDate, string Ordine)
        {
            if (ListaDate == null || !ListaDate.Any())
            {
                return ListaDate;
            }

            if (string.IsNullOrEmpty(Ordine))
            {
                return ListaDate;
            }

            var descrescator = Ordine.EndsWith("_desc");
            var propNume = descrescator ? Ordine.Substring(0, Ordine.Length - 5) : Ordine;
            Func<T, object> keySelector;

            if (propNume == "Parcela")
            {
                keySelector = item => typeof(T).GetProperty("Parcela")?.GetValue(item)?.GetType().GetProperty("CodParcela")?.GetValue(typeof(T).GetProperty("Parcela")?.GetValue(item));
            }
            else
               if (propNume == "Angajat")
            {
                keySelector = item => typeof(T).GetProperty("Angajat")?.GetValue(item)?.GetType().GetProperty("Nume")?.GetValue(typeof(T).GetProperty("Angajat")?.GetValue(item));
            }
            else
            {
                var propInfo = typeof(T).GetProperty(propNume);
                if (propInfo == null)
                {
                    return ListaDate;
                }
                keySelector = item => propInfo.GetValue(item);
            }
            if (descrescator)
            {
                ListaDate = ListaDate.OrderByDescending(keySelector).ToList();
            }
            else
            {
                ListaDate = ListaDate.OrderBy(keySelector).ToList();
            }
            return ListaDate;
        }
    }
}

ProiectLicenta/Views/RegistruFertilizare/Adaugare.cshtml
@using ProiectLicenta.ViewModels;
@model AddRegistruFertilizareViewModel;
@{
    ViewData["Title"] = "Adaugare Fertilizare";
}
<h1 class="  fw-bold pb-2 pb-xl-3 text-center">Adaugare Fertilizare</h1>
<div>
    <a class="btn btn-warning me-3" href="@Url.Action("Index", "RegistruFertilizare")"><i class="bi bi-arrow-left"></i> Inapoi</a>
    <div asp-controller="RegistruFertilizare" asp-action="Adaugare" class="bd-example">
    <form method="post">
            <div class="mb-3 mt-3">
                <select class="form-select form-control-lg" asp-for="CodParcela" asp-items="ViewBag.codParcela">
                 <option value="0" hidden>Alege Parcela</option>
            </select>
                <span class="text-danger" asp-validation-for="CodParcela"></span>
            </div>
            <div class=" form-floating mb-3">
                <input id="floatingInput" class="form-control" placeholder="Suprafata" asp-for="Suprafata" />
                <label for="floatingInput" asp-for="Suprafata">Suprafata</label>
                <span class="text-danger" asp-validation-for="Suprafata"></span>
            </div>
            <div class="mb-3">
                <select class="form-select form-control-lg" asp-for="CodAngajat" asp-items="ViewBag.codAngajat">
                 <option value="0" hidden>Alege Angajat</option>
            </select>
                <span class="text-danger" asp-validation-for="CodAngajat"></span>
            </div>
            <div class="form-floating date mb-3">
                <input type="date" id="floatingInput" class="form-control" placeholder="Data Fertilizare" asp-for="DataFertilizare" />
                <label for="floatingInput" asp-for="DataFertilizare">Data Fertilizare</label>
                <span class="text-danger" asp-validation-for="DataFertilizare"></span>
        </div>
            <div class="mb-3"> <label><input type="checkbox" asp-for="Stare" value="true" /> Sarcina Indeplinita</label></div>

            <input class="btn btn-primary" type="submit" value="Adaugare Fertilizare" />
    </form>
    </div>
</div>

ProiectLicenta/Views/RegistruFertilizare/Editare.cshtml
@using ProiectLicenta.ViewModels;
@model AddRegistruFertilizareViewModel;
@{
    ViewData["Title"] = "Editare Fertilizare";
}
<h1 class="  fw-bold pb-2 pb-xl-3 text-center"><i class="bi bi-pencil-fill"></i> Editare Fertilizare</h1>
<div>
    <a class="btn btn-warning me-3" href="@Url.Action("Index", "RegistruFertilizare")"><i class="bi bi-arrow-left"></i> Inapoi</a>
    <div asp-controller="RegistruFertilizare" asp-action="Editare" class="bd-example">
    <form method="post">
            <div class="mb-3 mt-3">
                <select class="form-select form-control-lg" asp-for="CodParcela" asp-items="ViewBag.codParcela">
                 <option value="0" hidden>Alege Parcela</option>
            </select>
                <span class="text-danger" asp-validation-for="CodParcela"></span>
            </div>
            <div class=" form-floating mb-3">
                <input id="floatingInput" class="form-control" placeholder="Suprafata" asp-for="Suprafata" />
                <label for="floatingInput" asp-for="Suprafata">Suprafata</label>
                <span class="text-danger" asp-validation-for="Suprafata"></span>
            </div>
            <div class="mb-3">
                <select class="form-select form-control-lg" asp-for="CodAngajat" asp-items="ViewBag.codAngajat">
                 <option value="0" hidden>Alege Angajat</option>
            </select>
                <span class="text-danger" asp-validation-for="CodAngajat"></span>
            </div>
            <div class="form-floating date mb-3">
                <input type="date" id="floatingInput" class="form-control" placeholder="Data Fertilizare" asp-for="DataFertilizare" />
                <label for="floatingInput" asp-for="DataFertilizare">Data Fertilizare</label>
                <span class="text-danger" asp-validation-for="DataFertilizare"></span>
        </div>
            <div>
                <input type="hidden" asp-for="CodFertilizare" />
            </div>
            <input class="btn btn-primary" type="submit" value="Editare Fertilizare" />
    </form>
    </div>
</div>

ProiectLicenta/Views/RegistruFertilizare/Index.cshtml
@using ProiectLicenta.Models
@model List<RegistruFertilizare>
@{
    ViewData["Title"] = "Registru Fertilizare";
     string currentSort = ViewBag.SortOrder != null ? ViewBag.SortOrder : "";
    string filtru = ViewBag.CurrentFilter != null ? ViewBag.CurrentFilter : "";
}
<h1 class="  fw-bold pb-2 pb-xl-3 text-center"><i class="bi bi-journals"></i> Registru Fertilizare </h1>
<div class="mb-3">
    <a class="btn btn-warning me-3" href="@Url.Action("Index", "Home")"><i class="bi bi-arrow-left"></i> Inapoi</a>
    <a class="btn btn-primary" asp-controller="RegistruFertilizare" asp-action="Adaugare"><i class="bi bi-plus-lg"></i> Adaugare</a>
    <a class="btn btn-danger float-end" asp-controller="RegistruFertilizare" asp-action="Stergere"><i class="bi bi-trash3"></i> Stergere</a>
</div>
<div class="mb-3">
    <form class="d-flex" asp-action="Index" method="get">
        <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
        <input class="form-control ms-2" type="search" placeholder="Cautare" aria-label="Cautare" name="searchString" value="@ViewBag.CurrentFilter">
    </form>
</div>
<div class="mb-3">
    <h4 hidden>Date</h4>
    <button class="btn btn-secondary mb-3" onclick="downloadTableAsHtml()"><i class="bi bi-file-earmark-arrow-down"></i> Descarca Continut</button>
</div>
<div>
@if (Model.Count == 0)
{
    <p> Nu exista fertilizari in registru!</p>
}
else
{
        <table class="table table-striped table-bordered" id="registruTable">
            <tr>
                <th colspan="2" class="fit-content">
                    Nr.
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "CodFertilizare" ? "CodFertilizare_desc" : "CodFertilizare",searchString = filtru })">
                        @if (currentSort != "CodFertilizare_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Parcela
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "Parcela" ? "Parcela_desc" : "Parcela",searchString = filtru })">
                        @if (currentSort != "Parcela_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Suprafata
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "Suprafata" ? "Suprafata_desc" : "Suprafata",searchString = filtru })">
                        @if (currentSort != "Suprafata_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Angajat
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "Angajat" ? "Angajat_desc" : "Angajat",searchString = filtru })">
                        @if (currentSort != "Angajat_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
                <th>
                    Data Fertilizare
                    <a href="@Url.Action("Index", new {sortOrder = currentSort == "DataFertilizare" ? "DataFertilizare_desc" : "DataFertilizare",searchString = filtru })">
                        @if (currentSort != "DataFertilizare_desc")
                        {
                            <i class="bi bi-sort-up"></i>
                        }
                        else
                        {
                            <i class="bi bi-sort-down"></i>
                        }
                    </a>
                </th>
            </tr>
        @foreach (var var in Model)
        {
                <tr>
                    <td class="fit-content">
                        <a href="@Url.Action("Editare", "RegistruFertilizare", new {id = var.CodFertilizare })"><i class="bi bi-pencil-fill link-primary"></i></a>
                    </td>
                    <td class="fit-content">
                       
                    @var.CodFertilizare
                </td>
                <td>
                    @var.Parcela.CodParcela | @var.Parcela.Locatie
                </td>
                <td>
                        @var.Suprafata &#x33A1;
                </td>
                <td>
                    @var.Angajat.Nume @var.Angajat.Prenume
                </td>
                <td>
                        @var.DataFertilizare.ToString("dd/MM/yyyy")
                    </td>
            </tr>
        }

    </table>
}</div>

ProiectLicenta/Views/RegistruFertilizare/Stergere.cshtml
@model List<RegistruFertilizare>
@{
    ViewData["Title"] = "Stergere Fertilizare";
}
<h1 class="  fw-bold pb-2 pb-xl-3 text-center"><i class="bi bi-trash3"></i> Sterge Fertilizare</h1>
<a class="btn btn-warning me-3" href="@Url.Action("Index", "RegistruFertilizare")"><i class="bi bi-arrow-left"></i> Inapoi</a>
<div class="mb-3 mt-3">
    <form class="d-flex" asp-action="Stergere" method="get">
        <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
        <input class="form-control ms-2" type="search" placeholder="Cautare" aria-label="Cautare" name="searchString" value="@ViewBag.CurrentFilter">
    </form>
</div>
<form method="post">
    <div class="mt-3">
        @if (Model.Count == 0)
        {
            <p>Nu exista Fertilizari!</p>
        }
        else
        {
            <table class="table table-striped table-bordered">
                <tr>
                    <th colspan="2" class="fit-content">
                        Nr.
                    </th>
                    <th>
                        Parcela
                    </th>
                    <th>
                        Suprafata
                    </th>
                    <th>
                        Angajat
                    </th>
                    <th>
                        Data Fertilizare
                    </th>
                    <th>Sarcina</th>
                </tr>
                @foreach (var var in Model)
                {
                    <tr>
                        <td>
                            <input type="checkbox" name="registruFertilizareId" value="@var.CodFertilizare" />
                        </td>
                        <td>
                            @var.CodFertilizare
                        </td>
                        <td>
                            @var.Parcela.Locatie
                        </td>
                        <td>
                            @var.Suprafata
                        </td>
                        <td>
                            @var.Angajat.Nume @var.Angajat.Prenume
                        </td>
                        <td>
                            @var.DataFertilizare.ToString("dd/MM/yyyy")
                        </td>
                        <td>
                            @if (var.Stare == false)
                            {
                                <i class="bi bi-three-dots"></i>
                            }
                            else
                            {
                                <i class="bi bi-check-lg"></i>
                            }
                        </td>
                    </tr>
                }
            </table>
        }
    </div>
    <input type="submit" value="Stergere" name="Stergere" class="btn btn-danger" />
</form>